// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0UivgnIO3Xz0pC2hzCmMeNln_fZqCx8k',
    appId: '1:908120428877:web:1a9ae63750951ee8e06704',
    messagingSenderId: '908120428877',
    projectId: 'projeto-modulo-flutter',
    authDomain: 'projeto-modulo-flutter.firebaseapp.com',
    storageBucket: 'projeto-modulo-flutter.appspot.com',
    measurementId: 'G-ZVNFHVBX3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF1i8t8eHdSr98IWxA5l4WUEEwAQqpU3U',
    appId: '1:908120428877:android:8ec4b12113f0a9e0e06704',
    messagingSenderId: '908120428877',
    projectId: 'projeto-modulo-flutter',
    storageBucket: 'projeto-modulo-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8kZhp_Kswj4bDNqCXxV84woUmnieo0go',
    appId: '1:908120428877:ios:9b2e500e3818ef4ce06704',
    messagingSenderId: '908120428877',
    projectId: 'projeto-modulo-flutter',
    storageBucket: 'projeto-modulo-flutter.appspot.com',
    iosClientId: '908120428877-vduja0r5jt5e5rs4qgl45so7nd6inghn.apps.googleusercontent.com',
    iosBundleId: 'br.edu.infnet.projeto.modulo.projetopesquisa',
  );
}
